// dom variables
const tagsEL = document.getElementById('tags')
const textarea = document.getElementById('textarea')

// timer variable
let timer = 100

// automatically put the cursor in the textarea
textarea.focus()

// event listener on textarea, listen for keyup
textarea.addEventListener('keyup', (e) => {
  // call createTags function
  // pass on the value of the keypress when it is released
  createTags(e.target.value)

  // conditional to check if enter on the keyboard pressed, then after 10ms clear the textarea input field
  if (e.key === 'Enter') {
    setTimeout(() => {
      e.target.value = ''
    }, 10)

    // call randomSelect function
    randomSelect()
  }
})

function createTags(input) {
  // capture the input from the text area and store in an array using split.  It will be separted by comma's
  // With map() we trim the input when it contains blanks on each side
  // With filter() we filter out the entries that have just empty strings
  // Map will remove white space on both sides
  const tags = input
    .split(',')
    .filter((tag) => tag.trim() !== '')
    .map((tag) => tag.trim())

  tagsEL.innerHTML = ''

  // loop through array of tags
  tags.forEach((tag) => {
    // create a span
    const tagEL = document.createElement('span')

    // add the class of tag to the tagEL span
    tagEL.classList.add('tag')
    // set the value of the tag to the text value
    tagEL.innerText = tag
    // add each tag span to the tags container
    tagsEL.appendChild(tagEL)
  })
}

function randomSelect() {
  // variable for number of times to highlight span
  const times = 30

  //function that creates the random highlighting on the tags
  const interval = setInterval(() => {
    // call pickRandomTag and store in randomTag Variable
    const randomTag = pickRandomTag()

    // call HighlightTag and pass in randomTag value
    higlightTag(randomTag)

    // wait 100ms to call unhilight function
    setTimeout(() => {
      unhiglightTag(randomTag)
    }, timer)

    // -------------------------------------
  }, timer)

  // stops the invterval function from running
  // stops on a random tag
  setTimeout(() => {
    clearInterval(interval)

    // pick a random tag to stop on
    setTimeout(() => {
      const randomTag = pickRandomTag()

      higlightTag(randomTag)
    })
  }, times * timer)
}

function pickRandomTag() {
  // store all the .tags spans in a nodelist which is similar to an array
  const tags = document.querySelectorAll('.tag')

  // return a random number in the tags nodelist.array
  // Math.random generates a value between 0-1
  // Multiply the length of the array between a value generated by Math.Random
  // Math.floor will round the number down
  // example return tags[5] (value at index 5 is returned)
  return tags[Math.floor(Math.random() * tags.length)]
}

function higlightTag(tag) {
  // apply the highlight class to tag
  tag.classList.add('highlight')
}

function unhiglightTag(tag) {
  // remove the highlight class on tag
  tag.classList.remove('highlight')
}
